### ISSUE TITLE
Empty list as a counter example

### ISSUE THREAD

**Issue by asd1o2487c** [alfert/propcheck#43]
When running the following test

```elixir
defmodule PropTest do
  use ExUnit.Case, async: true

  describe "using propcheck" do
    use PropCheck

    property "natural numbers are non-negative" do
      quickcheck(
        forall n <- nat() do
          n >= 1
        end
      )
    end
  end
end
```

I get
```elixir
⟩ mix test
..!
Failed: After 3 test(s).
0

Shrinking (0 time(s))
0


  1) property using propcheck natural numbers are non-negative (PropTest)
     test/prop_test.exs:7
     Property Elixir.PropTest.property using propcheck natural numbers are non-negative() failed. Counter-Example is:
     [] # <--- this

     code: nil
     stacktrace:
       (propcheck) lib/properties.ex:107: PropCheck.Properties.handle_check_results/3
       test/prop_test.exs:7: (test)



Finished in 0.09 seconds
1 property, 1 failure

Randomized with seed 234247
```

Why is `Counter-Example` and empty list `[]`? Should it have a `0` in it or be a `0`?

**Comment by alfert** [comment]
The `quickcheck` command is not needed. Try this: 

```elixir
property "natural numbers are non-negative" do
  forall n <- nat() do
    n >= 1
  end
end
```

**Comment by alfert** [comment]
The counter examples are shown above in your code. It is first a `0` (after 3 tests), then it is shrinked to `0` again. I am unsure why exactly this is not reported properly in the summary without reading the code, but I am pretty sure that the `quickcheck` function does not follow the contract of `forall` and thus does not report the same information towards the `property` macro, which does the reporting. Please try the variant without the `quickcheck` function and everything should be cool.

**Comment by asd1o2487c** [comment]
Removing `quickcheck` seems to work, thank you! 

```elixir
  1) property using propcheck natural numbers are non-negative (PropTest)
     test/prop_test.exs:7
     Property Elixir.PropTest.property using propcheck natural numbers are non-negative() failed. Counter-Example is:
     [0]

     code: nil
     stacktrace:
       (propcheck) lib/properties.ex:107: PropCheck.Properties.handle_check_results/3
       test/prop_test.exs:7: (test)



Finished in 0.1 seconds
1 property, 1 failure

Randomized with seed 884207
```
