### ISSUE TITLE
let_shrink only accepts two elements

### ISSUE THREAD

**Issue by ferd** [alfert/propcheck#49]
Sample session: 

```
iex(15)>     let_shrink([
...(15)>       appetizer <- elements([:soup, :salad, :cheesesticks]),
...(15)>       dessert <- elements([:cake, :chocolate, :icecream])
...(15)>     ]) do
...(15)>       [appetizer, dessert]
...(15)>     end

<works>

iex(16)>     let_shrink([
...(16)>       appetizer <- elements([:soup, :salad, :cheesesticks]),
...(16)>       drink <- elements([:coffee, :tea, :milk, :water, :juice]),
...(16)>       dessert <- elements([:cake, :chocolate, :icecream])
...(16)>     ]) do
...(16)>       [appetizer, drink, dessert]
...(16)>     end

** (ArgumentError) argument error
    (propcheck) lib/propcheck.ex:693: anonymous fn/1 in PropCheck."MACRO-let_shrink"/3
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (propcheck) expanding macro: PropCheck.let_shrink/2
    iex:16: (file)
```

I'm not exactly sure why, but it appears that only those calls with two elements work.
``` 
let_shrink([a <- 1]) do 0 end ==========================> fails
let_shrink([a <- 1, b <- 2]) do 0 end ==================> works
let_shrink([a <- 1, b <- 2, c <- 3]) do 0 end ==========> fails
let_shrink([a <- 1, b <- 2, c <- 3, d <- 4]) do 0 end ==> fails
```

**Comment by alfert** [comment]
This is a duplicate of #47, because both, `let_shrink` and `let` share the same implementation for processing the bound variables. Already resolved in `master`, a bug-fix release is in preparation.

**Comment by ferd** [comment]
Alright. Thanks!
