### ISSUE TITLE
Importing `TargetedPBT.setup/2` can conflict with `ExUnit.Callbacks.setup/2`

### ISSUE THREAD

**Issue by evnu** [alfert/propcheck#83]
Both `ExUnit.Callbacks` and `PropCheck.TargetedPBT` export `setup/2`, which can conflict.

Mix:

```elixir
# mix.exs
defmodule Repro.MixProject do
  use Mix.Project

  def project do
    [
      app: :repro,
      version: "0.1.0",
      elixir: "~> 1.7",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:propcheck, "~> 1.1.3"}
    ]
  end
end
```

Test:

```elixir
defmodule ReproTest do
  use ExUnit.Case
  use PropCheck

  setup _a do
    []
  end

  test "greets the world" do
    assert Repro.hello() == :world
  end
end
```

Error:

```
== Compilation error in file test/repro_test.exs ==
** (CompileError) test/repro_test.exs:5: function setup/2 imported from both PropCheck.TargetedPBT and ExUnit.Callbacks, call is ambiguous
    (elixir) src/elixir_dispatch.erl:111: :elixir_dispatch.expand_import/6
    (elixir) src/elixir_dispatch.erl:81: :elixir_dispatch.dispatch_import/5
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
[1]    1127 exit 1     mix test
```

**Comment by alfert** [comment]
Ouch, that's not nice.

**Comment by alfert** [comment]
I did not look close enough on the source code from proper 1.3: There is as a new feature the macro `setup` which I only related to old targeted property based testing code. Since it may be helpful to have this feature also available in Elixir, I propose a different solution than not exporting it: It should available as `property_setup` including documentation.

**Comment by evnu** [comment]
Can this be released soon?

**Comment by alfert** [comment]
Yes, I want to release it today.

Von unterwegs  gesendet

**Comment by alfert** [comment]
> Can this be released soon?

Release 1.1.4 is out, version 1.1.3 is retired in hex.pm
